Add always_publish arg
jsk-ros-pkg/coral_usb_ros pull request #134
Opened 2023-06-26 08:00 UTC by tkmtnt7000

2023-06-26 13:47 UTC, sktometometo approved these changes

2023-06-26 15:13 UTC, knorth55 requested changes

2023-06-26 15:14 UTC, knorth55 commented
please update the doc in readme.md

2023-06-26 22:48 UTC, sktometometo commented on python/coral_usb/node_base.py
> +            "Publish even if object/human_pose is not found : {}".format(
It also mentioned 'object'.

2023-06-27 03:51 UTC, knorth55 commented on python/coral_usb/node_base.py
> +            "Publish even if object/human_pose is not found : {}".format(
oh, I see.

2023-06-27 04:21 UTC, tkmtnt7000 commented on python/coral_usb/human_pose_estimator.py
> +            return
Thank you. I updated in [d8f61e9](https://github.com/jsk-ros-pkg/coral_usb_ros/pull/134/commits/d8f61e9957df8ffdfa4601dd487b68016e7e23ad)

2023-06-27 04:30 UTC, tkmtnt7000 commented
Thank you for reviewing. 
I update the document.

2023-06-27 20:00 UTC, knorth55 approved these changes

2023-12-15 17:52 UTC, merged